<a href="https://colab.research.google.com/github/Sebas1020h/Pandas-transformacion-y-manipulacion-de-datos/blob/main/Pandas_Tratamiento_Manipulacion_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**PROBLEMA DE NEGOCIO**


---

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [86]:
ruta_aula_1 = "/content/drive/MyDrive/Classroom/Alura/Pandas-transformacion-y-manipulacion-de-datos/2071-ProyectoFinal/data/"

Se trata de un algoritmo capaz de analizar las características de una propiedad -como comodidades, tamaño, ocupación del espacio en un período determinado- y sugerir al anfitrión un precio a cobrar por tarifas diarias que garantice ganancias en momentos de alta demanda.

#**1. Entendiendo el Problema**


---

In [5]:
import pandas as pd

In [6]:
datos = pd.read_json(ruta_aula_1 + 'datos_hosting.json')
datos.head()

                                      info_inmuebles
0  {'evaluacion_general': '10.0', 'experiencia_lo...
1  {'evaluacion_general': '10.0', 'experiencia_lo...
2  {'evaluacion_general': '10.0', 'experiencia_lo...
3  {'evaluacion_general': '10.0', 'experiencia_lo...
4  {'evaluacion_general': '10.0', 'experiencia_lo...

In [7]:
datos = pd.json_normalize(datos['info_inmuebles'])
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

In [8]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    70 non-null     object
 1   experiencia_local     70 non-null     object
 2   max_hospedes          70 non-null     object
 3   descripcion_local     70 non-null     object
 4   descripcion_vecindad  70 non-null     object
 5   cantidad_baños        70 non-null     object
 6   cantidad_cuartos      70 non-null     object
 7   cantidad_camas        70 non-null     object
 8   modelo_cama           70 non-null     object
 9   comodidades           70 non-null     object
 10  cuota_deposito        70 non-null     object
 11  cuota_limpieza        70 non-null     object
 12  precio                70 non-null     object
dtypes: object(13)
memory usage: 7.2+ KB

## Desafio 1 Aula 1

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que más gastaron en productos durante los 5 días de ventas, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esta semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

La base de datos utilizada en este análisis es dados_vendas_clientes.json (Esta guardada en la carpeta DB_Desafios) y contiene información importante sobre los clientes, como el nombre registrado del cliente, el monto total pagado al momento de la compra y el día de la compra.

Sabiendo esta información, el desafío del proyecto 1: ventas online será abrir la base de datos con Pandas y aplicar json_normalize.

In [9]:
import pandas as pd
ruta_Desafio_1_Aula_1 = "/content/drive/MyDrive/Classroom/Alura/Pandas-transformacion-y-manipulacion-de-datos/DB_Desafios/dados_vendas_clientes.json"

In [10]:
ventas_online = pd.read_json(ruta_Desafio_1_Aula_1)
ventas_online.head()

                                        dados_vendas
0  {'Data de venda': '06/06/2022', 'Cliente': ['@...
1  {'Data de venda': '07/06/2022', 'Cliente': ['I...
2  {'Data de venda': '08/06/2022', 'Cliente': ['I...
3  {'Data de venda': '09/06/2022', 'Cliente': ['J...
4  {'Data de venda': '10/06/2022', 'Cliente': ['M...

In [11]:
ventas_online_norm = pd.json_normalize(ventas_online['dados_vendas'])
ventas_online_norm.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

## Desafio 2 Aula 1

Administrar condominios es una tarea que requiere mucha atención y organización. Entre las diversas responsabilidades de gestión se encuentra el cobro del alquiler a los inquilinos. Para garantizar la buena salud financiera de la empresa, es fundamental que estos pagos se realicen de forma regular y puntual. Sin embargo, sabemos que esto no siempre sucede.

Teniendo esto en cuenta, propongo un desafío de procesamiento de datos con el objetivo de analizar el retraso en el pago del alquiler en el condominio de algunos residentes. Pongo a disposición la base de datos dados_locacao_imoveis.json (Esta guardada en la carpeta DB_Desafios), que contiene información sobre el departamento de los inquilinos, el día acordado para el pago del alquiler, el día en que se realiza el pago del alquiler y el monto del alquiler.

Con esta información, el desafío del proyecto 2: administración del condominio será similar al desafío del proyecto 1, abrir la base de datos con Pandas y aplicar json_normalize al DataFrame.

In [12]:
import pandas as pd
ruta_Desafio_2_Aula_1 = "/content/drive/MyDrive/Classroom/Alura/Pandas-transformacion-y-manipulacion-de-datos/DB_Desafios/dados_locacao_imoveis.json"

In [13]:
administracion_condominio = pd.read_json(ruta_Desafio_2_Aula_1)
administracion_condominio.head()

                                       dados_locacao
0  {'apartamento': 'A101 (blocoAP)', 'datas_combi...
1  {'apartamento': 'A102 (blocoAP)', 'datas_combi...
2  {'apartamento': 'B201 (blocoAP)', 'datas_combi...
3  {'apartamento': 'B202 (blocoAP)', 'datas_combi...
4  {'apartamento': 'C301 (blocoAP)', 'datas_combi...

In [14]:
administracion_condominio_norm = pd.json_normalize(administracion_condominio['dados_locacao'])
administracion_condominio_norm.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

#**2. Datos numéricos**


---

In [15]:
import pandas as pd

In [16]:
columnas = list(datos.columns)
columnas

['evaluacion_general',
 'experiencia_local',
 'max_hospedes',
 'descripcion_local',
 'descripcion_vecindad',
 'cantidad_baños',
 'cantidad_cuartos',
 'cantidad_camas',
 'modelo_cama',
 'comodidades',
 'cuota_deposito',
 'cuota_limpieza',
 'precio']

In [17]:
datos = datos.explode(columnas[3:])
datos

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [18]:
datos.reset_index(inplace = True, drop = True)
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

In [19]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [20]:
import numpy as np

In [21]:
datos['max_hospedes'] = datos['max_hospedes'].astype(np.int64)

In [22]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   object
 6   cantidad_cuartos      3818 non-null   object
 7   cantidad_camas        3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [23]:
col_numericas = ['cantidad_baños', 'cantidad_cuartos', 'cantidad_camas']

In [24]:
datos[col_numericas] = datos[col_numericas].astype(np.int64)

In [25]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [26]:
datos['evaluacion_general'] = datos['evaluacion_general'].astype(np.float64)

In [27]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [28]:
datos['precio'] = datos['precio'].apply(lambda x: x.replace('$','').replace(',','').strip())
datos['precio']

0       110.00
1        45.00
2        55.00
3        52.00
4        85.00
         ...
3813    299.00
3814    199.00
3815    400.00
3816    250.00
3817    350.00
Name: precio, Length: 3818, dtype: object

In [29]:
datos['precio'] = datos['precio'].astype(np.float64)

In [30]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   object
 11  cuota_limpieza        3818 non-null   object
 12  precio                3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [31]:
datos[['cuota_deposito', 'cuota_limpieza']] = datos[['cuota_deposito', 'cuota_limpieza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

/tmp/ipython-input-31-2696303735.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  datos[['cuota_deposito', 'cuota_limpieza']] = datos[['cuota_deposito', 'cuota_limpieza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

In [32]:
datos[['cuota_deposito', 'cuota_limpieza']] = datos[['cuota_deposito', 'cuota_limpieza']].astype(np.float64)

In [33]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   evaluacion_general    3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descripcion_local     3818 non-null   object
 4   descripcion_vecindad  3818 non-null   object
 5   cantidad_baños        3818 non-null   int64
 6   cantidad_cuartos      3818 non-null   int64
 7   cantidad_camas        3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  cuota_deposito        3818 non-null   float64
 11  cuota_limpieza        3818 non-null   float64
 12  precio                3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

## Desafio 1 Aula 2
Leímos la base de datos en el desafío anterior, ahora podemos seguir adelante con la transformación de estos datos. Así, el nuevo desafío del proyecto 1 será dividido en algunas metas:

* Eliminar datos en listas dentro del DataFrame.
* Verificar tipos de datos.
* Identificar columnas numéricas.
* Transformar la columna numérica a tipo numérico.

In [34]:
import pandas as pd
import numpy as np

In [35]:
ventas_online_norm

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [36]:
col_ventas_online_series = list(ventas_online_norm.columns)
col_ventas_online_series

['Data de venda', 'Cliente', 'Valor da compra']

In [37]:
ventas_online_norm_2 = ventas_online_norm.explode(col_ventas_online_series[1:])
ventas_online_norm_2.reset_index(inplace = True, drop = True)
ventas_online_norm_2

   Data de venda             Cliente Valor da compra
0     06/06/2022     @ANA _LUCIA 321        R$ 836,5
1     06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2     06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3     06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4     07/06/2022  Isabely JOanes 738       R$ 825,31
5     07/06/2022  Isabely JOanes 738       R$ 168,07
6     07/06/2022  Isabely JOanes 738       R$ 339,18
7     07/06/2022  Isabely JOanes 738       R$ 314,69
8     08/06/2022  Isabely JOanes 738       R$ 682,05
9     08/06/2022    JOãO Gabriel 671       R$ 386,34
10    08/06/2022  Julya meireles 914       R$ 622,65
11    08/06/2022  Julya meireles 914       R$ 630,79
12    09/06/2022  Julya meireles 914        R$ 390,3
13    09/06/2022     MaRIA Julia 444       R$ 759,16
14    09/06/2022     MaRIA Julia 444       R$ 334,47
15    09/06/2022     MaRIA Julia 444       R$ 678,78
16    10/06/2022     MaRIA Julia 444       R$ 314,24
17    10/06/2022     PEDRO PASCO 812       R$ 311,15
18    10/06/2022    Paulo castro 481       R$ 899,16
19    10/06/2022   Thiago fritzz 883       R$ 885,24

In [38]:
ventas_online_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [39]:
ventas_online_norm_2["Valor da compra"] = ventas_online_norm_2["Valor da compra"].apply(lambda x: x.replace('R$','').replace(',','.').strip())
ventas_online_norm_2["Valor da compra"] = ventas_online_norm_2["Valor da compra"].astype(np.float64)
ventas_online_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 612.0+ bytes

## Desafio 2 Aula 2
Leímos la base de datos en el desafío anterior, ahora podemos seguir adelante con la transformación de estos datos. Entonces, de la misma manera que en el proyecto 1, el desafío del proyecto 2 está listado en algunas metas:

* Eliminar datos en listas dentro del DataFrame.
* Verificar tipos de datos.
* Identificar columnas numéricas.
* Transformar la columna numérica a tipo numérico.

In [40]:
administracion_condominio_norm

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [41]:
col_administracion_condominio_norm = list(administracion_condominio_norm.columns)
col_administracion_condominio_norm

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [42]:
administracion_condominio_norm_2 = administracion_condominio_norm.explode(col_administracion_condominio_norm[1:])
administracion_condominio_norm_2.reset_index(inplace = True, drop = True)
administracion_condominio_norm_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
5,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
6,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
7,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
8,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
9,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
10,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
11,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
12,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
13,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
14,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
15,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
16,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
17,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
18,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
19,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
20,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
21,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
22,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
23,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
24,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
25,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
26,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
27,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
28,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
29,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

In [43]:
administracion_condominio_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [44]:
administracion_condominio_norm_2['valor_aluguel']

0     $ 1000,0 reais
1     $ 2500,0 reais
2     $ 1100,0 reais
3     $ 2600,0 reais
4     $ 1200,0 reais
5     $ 2700,0 reais
6     $ 1300,0 reais
7     $ 2800,0 reais
8     $ 1400,0 reais
9     $ 2900,0 reais
10    $ 1500,0 reais
11    $ 1200,0 reais
12    $ 1600,0 reais
13    $ 1300,0 reais
14    $ 1700,0 reais
15    $ 1400,0 reais
16    $ 1800,0 reais
17    $ 1500,0 reais
18    $ 1900,0 reais
19    $ 1600,0 reais
20    $ 2000,0 reais
21    $ 1000,0 reais
22    $ 2100,0 reais
23    $ 1100,0 reais
24    $ 2200,0 reais
25    $ 1200,0 reais
26    $ 2300,0 reais
27    $ 2100,0 reais
28    $ 2400,0 reais
29    $ 2200,0 reais
Name: valor_aluguel, dtype: object

In [45]:
administracion_condominio_norm_2['valor_aluguel'] = administracion_condominio_norm_2['valor_aluguel'].apply(lambda x: x.replace('$ ', '').replace(' reais', '').replace(',','.').strip())
administracion_condominio_norm_2['valor_aluguel'] = administracion_condominio_norm_2['valor_aluguel'].astype(np.float64)
administracion_condominio_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB

#**3. Datos de texto**


---

In [46]:
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [47]:
datos['descripcion_local'] = datos['descripcion_local'].str.lower()

In [48]:
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,this clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,our century old upper queen anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,very lovely and cozy room for one. convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,the “studio at mibbett hollow' is in a beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [49]:
datos['descripcion_local'][3169]

"built, run and supported by seattle tech and start up veterans, grokhome's focus is to create a supportive environment for smart people working on interesting projects, start ups and more. this listing is an upper bunk, in a 2-person shared room. *note: this fall, there will be major renovations happening on one kitchen and bathroom at a time. there will always be two other working kitchens and two working bathrooms in the house. we'll work to minimize the impact these renovations have on your stay. **this listing is only available to those working in the tech/science space. live in a hacker house, and immerse yourself in the seattle tech scene. you can expect to be surrounded by smart people solving big problems or working on something fun. we have frequent demo nights, and love when our guests share something they are passionate about. if you're new to the city, our deep ties to the seattle tech scene can help you get involved. expand your network, develop your ideas, and learn somet"

In [50]:
datos['descripcion_local'] = datos['descripcion_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)

In [51]:
datos['descripcion_local'] = datos['descripcion_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [52]:
datos['descripcion_local'].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one  convenientl...
4    the  studio at mibbett hollow' is in a beautif...
Name: descripcion_local, dtype: object

In [53]:
datos['descripcion_local'] = datos['descripcion_local'].str.split()
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

In [54]:
datos['comodidades'] = datos['comodidades'].str.replace('\{|}|\"','', regex=True)

In [55]:
datos['comodidades'] = datos['comodidades'].str.split(',')
datos.head()

,evaluacion_general,experiencia_local,max_hospedes,descripcion_local,descripcion_vecindad,cantidad_baños,cantidad_cuartos,cantidad_camas,modelo_cama,comodidades,cuota_deposito,cuota_limpieza,precio
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.0

## Desafio 1 Aula 3

 realizar el proceso de tokenización para la columna descripcion_vecindad presente en el conjunto de datos datos_hosting.json.

In [56]:
datos['descripcion_vecindad'][34]

"Magnolia is a lovely neighborhood just minutes from downtown Seattle. My home is a 10 minute walk/2 minute drive to the main street area of Magnolia, known as the Village. There you can find several coffee shops, a bakery, bookstore, grocery store, drug store, gas station, and several boutiques. Restaurants include, Chinese, Mexican, Italian (fantastic wood-fired pizza!), Thai and Rogo's-a Seattle institution. There is also a Whole Foods about 1 1/2 miles away.  Discovery Park is a 5 minute drive from the house - a huge park with plenty of trails and gorgeous views of Puget Sound. A trail runner's paradise and great for walkers or a trip down to the beach.  This is a quiet and safe residential area."

In [57]:
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.lower().replace('[^a-zA-Z0-9\-\']',' ',regex=True).replace('(?<!\w)-(?!\w)',' ',regex=True)

In [58]:
datos['descripcion_vecindad'] = datos['descripcion_vecindad'].str.split()

In [59]:
datos['descripcion_vecindad']

0       [lower, queen, anne, is, near, the, seattle, c...
1       [upper, queen, anne, is, a, really, pleasant, ...
2       [the, convenience, of, being, in, seattle, but...
3       [ballard, is, lovely, vibrant, and, one, of, t...
4                                                      []
                              ...
3813                                                   []
3814    [quiet, dead, end, street, near, i-5, the, pro...
3815                                                   []
3816    [your, hosts, made, madison, valley, their, ho...
3817    [despite, the, quiet, leafy, streets, of, this...
Name: descripcion_vecindad, Length: 3818, dtype: object

## Desafio 2 Aula 3

 Debido a una inestabilidad en el sitio web de la empresa, tuvimos problemas con los nombres de los clientes durante el guardado. Esto resultó en una columna de nombres de clientes con una combinación de letras, mayúsculas y minúsculas, números y otros caracteres.

Sabiendo esto, manipula los textos de la columna Cliente para que el resultado sean los nombres de los clientes en letras minúsculas, con ausencia de caracteres especiales o números.

In [60]:
import pandas as pd
import numpy as np

In [61]:
ventas_online_norm_2

   Data de venda             Cliente  Valor da compra
0     06/06/2022     @ANA _LUCIA 321           836.50
1     06/06/2022  DieGO ARMANDIU 210           573.33
2     06/06/2022  DieGO ARMANDIU 210           392.80
3     06/06/2022  DieGO ARMANDIU 210           512.34
4     07/06/2022  Isabely JOanes 738           825.31
5     07/06/2022  Isabely JOanes 738           168.07
6     07/06/2022  Isabely JOanes 738           339.18
7     07/06/2022  Isabely JOanes 738           314.69
8     08/06/2022  Isabely JOanes 738           682.05
9     08/06/2022    JOãO Gabriel 671           386.34
10    08/06/2022  Julya meireles 914           622.65
11    08/06/2022  Julya meireles 914           630.79
12    09/06/2022  Julya meireles 914           390.30
13    09/06/2022     MaRIA Julia 444           759.16
14    09/06/2022     MaRIA Julia 444           334.47
15    09/06/2022     MaRIA Julia 444           678.78
16    10/06/2022     MaRIA Julia 444           314.24
17    10/06/2022     PEDRO PASCO 812           311.15
18    10/06/2022    Paulo castro 481           899.16
19    10/06/2022   Thiago fritzz 883           885.24

In [85]:
nombres_clientes = ventas_online_norm_2["Cliente"].str.lower().replace('[^a-z ]', '', regex=True).str.strip()
ventas_online_norm_2["Cliente"] = ventas_online_norm_2["Cliente"].str.lower().replace('[^a-z ]', '', regex=True).str.strip()
nombres_clientes

0          ana lucia
1     diego armandiu
2     diego armandiu
3     diego armandiu
4     isabely joanes
5     isabely joanes
6     isabely joanes
7     isabely joanes
8     isabely joanes
9        joo gabriel
10    julya meireles
11    julya meireles
12    julya meireles
13       maria julia
14       maria julia
15       maria julia
16       maria julia
17       pedro pasco
18      paulo castro
19     thiago fritzz
Name: Cliente, dtype: object

## Desafio 3 Aula 3

 Buscando explicar la organización de la identificación de los apartamentos, durante la creación del conjunto de datos se añadió el texto (blocoAP). Este texto informa que los nombres de los apartamentos están organizados con la letra mayúscula seguida del número del apartamento. Sin embargo, esto no aporta ninguna información a nuestros datos, por lo que resulta interesante eliminar este texto del conjunto de datos.

Con esto, manipule los textos de la columna apartamento para eliminar el texto (blocoAP) del DataFrame.

In [77]:
administracion_condominio_norm_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
1,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
2,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
3,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
4,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
5,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
6,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
7,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
8,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
9,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
10,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
11,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
12,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
13,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
14,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
15,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
16,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
17,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
18,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
19,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
20,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
21,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
22,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
23,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
24,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
25,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
26,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
27,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
28,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
29,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [84]:
apartamento = administracion_condominio_norm_2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
administracion_condominio_norm_2['apartamento'] = administracion_condominio_norm_2['apartamento'].str.replace(' \(blocoAP\)', '', regex=True)
apartamento

0     A101
1     A101
2     A102
3     A102
4     B201
5     B201
6     B202
7     B202
8     C301
9     C301
10    C302
11    C302
12    D401
13    D401
14    D402
15    D402
16    E501
17    E501
18    E502
19    E502
20    F601
21    F601
22    F602
23    F602
24    G701
25    G701
26    G702
27    G702
28    H801
29    H801
Name: apartamento, dtype: object

#**4. Datos de tiempo**


---

In [136]:
import pandas as pd

In [137]:
dt_data = pd.read_json(ruta_aula_1 + 'inmuebles_disponibles.json')
dt_data.head()

    id       fecha  lugar_disponible precio
0  857  2016-01-04             False   None
1  857  2016-01-05             False   None
2  857  2016-01-06             False   None
3  857  2016-01-07             False   None
4  857  2016-01-08             False   None

In [93]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  object
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [139]:
dt_data['fecha'] = pd.to_datetime(dt_data['fecha'])

In [95]:
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [145]:
dt_data.sample(10)

          id      fecha  lugar_disponible   precio
4929    2810 2016-07-06              True   $60.00
140476   604 2016-11-15              True  $135.00
357970    20 2016-09-30              True  $120.00
221269  1606 2016-03-23              True   $42.00
217045  3712 2016-08-26              True   $85.00
17394    813 2016-08-30             False      0.0
289154  1139 2016-03-18              True  $120.00
362886  3389 2016-03-20              True  $102.00
43116    890 2016-02-19             False      0.0
25442   3673 2016-09-17              True  $122.00

In [140]:
dt_data['fecha'].dt.strftime('%Y-%m')

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: fecha, Length: 365000, dtype: object

In [141]:
subset = dt_data.groupby(dt_data['fecha'].dt.strftime('%Y-%m'))['lugar_disponible'].sum()
subset

fecha
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: lugar_disponible, dtype: int64

## Desafio 1 Aula 4

Durante las clases de este curso, descubrimos cómo transformar y trabajar con valores numéricos, por ejemplo, eliminando valores numéricos dentro de un texto y transformándolos en un tipo numérico, como int64 o float64.

Sabiendo esto, en esta actividad te propongo transformar los datos de la columna precio del conjunto de datos inmuebles_disponibles.json al tipo numérico float64. Recordando que, antes de hacer esto, debes llenar los valores vacíos de la columna con un valor. Una sugerencia: reemplazar con el string '0.0'.

In [109]:
import numpy as np

In [146]:
dt_data['precio'].fillna("0.0", inplace=True)
dt_data['precio']

0             0.0
1             0.0
2             0.0
3             0.0
4             0.0
           ...
364995    $140.00
364996    $140.00
364997    $140.00
364998    $140.00
364999        0.0
Name: precio, Length: 365000, dtype: object

In [147]:
dt_data['precio'] = dt_data['precio'].apply(lambda x: x.replace('$', '').replace(',',''))
dt_data['precio']

0            0.0
1            0.0
2            0.0
3            0.0
4            0.0
           ...
364995    140.00
364996    140.00
364997    140.00
364998    140.00
364999       0.0
Name: precio, Length: 365000, dtype: object

In [148]:
dt_data['precio'] = dt_data['precio'].astype(np.float64)
dt_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   id                365000 non-null  int64
 1   fecha             365000 non-null  datetime64[ns]
 2   lugar_disponible  365000 non-null  bool
 3   precio            365000 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(1), int64(1)
memory usage: 11.5 MB

## Desafio 2 Aula 4

En los pasos anteriores ya hemos trabajado con varios tipos de datos, ahora podemos trabajar con datos de tiempo.

En la columna Fecha de venta tenemos fechas en el formato 'día/mes/año' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualización de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

Si no recuerdas el problema del Proyecto Desafío 1, te dejo el texto de la situación a continuación para que sea más fácil encontrar la información:

El objetivo de este proyecto es analizar los resultados de un evento con los clientes de una empresa de venta online. Se recopiló un conjunto de datos que contiene los clientes que gastaron más en productos dentro de los 5 días posteriores a la venta, que es la duración del evento. Este análisis identificará al cliente con la mayor compra esa semana, quien recibirá un premio de la tienda, y posteriormente, puede ayudar a la empresa a crear nuevas estrategias para atraer más clientes.

In [150]:
ventas_online_norm_2

   Data de venda         Cliente  Valor da compra
0     06/06/2022       ana lucia           836.50
1     06/06/2022  diego armandiu           573.33
2     06/06/2022  diego armandiu           392.80
3     06/06/2022  diego armandiu           512.34
4     07/06/2022  isabely joanes           825.31
5     07/06/2022  isabely joanes           168.07
6     07/06/2022  isabely joanes           339.18
7     07/06/2022  isabely joanes           314.69
8     08/06/2022  isabely joanes           682.05
9     08/06/2022     joo gabriel           386.34
10    08/06/2022  julya meireles           622.65
11    08/06/2022  julya meireles           630.79
12    09/06/2022  julya meireles           390.30
13    09/06/2022     maria julia           759.16
14    09/06/2022     maria julia           334.47
15    09/06/2022     maria julia           678.78
16    10/06/2022     maria julia           314.24
17    10/06/2022     pedro pasco           311.15
18    10/06/2022    paulo castro           899.16
19    10/06/2022   thiago fritzz           885.24

In [154]:
ventas_online_norm_2['Data de venda'] = pd.to_datetime(ventas_online_norm_2['Data de venda'], format='%d/%m/%Y')
ventas_online_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     datetime64[ns]
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 612.0+ bytes

In [156]:
total_compras = ventas_online_norm_2.groupby(["Cliente"])["Valor da compra"].sum()
total_compras

Cliente
ana lucia          836.50
diego armandiu    1478.47
isabely joanes    2329.30
joo gabriel        386.34
julya meireles    1643.74
maria julia       2086.65
paulo castro       899.16
pedro pasco        311.15
thiago fritzz      885.24
Name: Valor da compra, dtype: float64

## Desafio 3 Aula 4

Al igual que en el Proyecto Desafío 1, trabajamos con todas las columnas excepto las que involucran fechas.

En las columnas datas_de_pagamento y datas_combinadas_pagamento tenemos fechas en el formato 'día/mes/año' (dd/mm/AAAA). Transforme estos datos al tipo datetime y busque una forma de visualización de subconjunto que pueda contribuir al objetivo del contexto en el que se insertan los datos.

Si no recuerdas el problema del Proyecto Desafío 2, te dejo el texto de la situación a continuación para que sea más fácil encontrar la información:

Administrar condominios es una tarea que requiere mucha atención y organización. Entre las diversas responsabilidades de gestión se encuentra el cobro del alquiler a los inquilinos. Para garantizar la buena salud financiera de la empresa, es fundamental que estos pagos se realicen de forma regular y puntual. Sin embargo, sabemos que esto no siempre sucede. Teniendo esto en cuenta, propongo un desafío de procesamiento de datos con el objetivo de analizar el retraso en el pago de la renta en el condominio ficticio de algunos residentes.

In [157]:
administracion_condominio_norm_2

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0         A101                 01/06/2022         05/06/2022         1000.0
1         A101                 01/07/2022         03/07/2022         2500.0
2         A102                 02/06/2022         02/06/2022         1100.0
3         A102                 02/07/2022         06/07/2022         2600.0
4         B201                 03/06/2022         07/06/2022         1200.0
5         B201                 03/07/2022         03/07/2022         2700.0
6         B202                 04/06/2022         07/06/2022         1300.0
7         B202                 04/07/2022         05/07/2022         2800.0
8         C301                 05/06/2022         10/06/2022         1400.0
9         C301                 05/07/2022         09/07/2022         2900.0
10        C302                 06/06/2022         08/06/2022         1500.0
11        C302                 06/07/2022         12/07/2022         1200.0
12        D401                 07/06/2022         07/06/2022         1600.0
13        D401                 07/07/2022         09/07/2022         1300.0
14        D402                 08/06/2022         10/06/2022         1700.0
15        D402                 08/07/2022         14/07/2022         1400.0
16        E501                 09/06/2022         10/06/2022         1800.0
17        E501                 09/07/2022         09/07/2022         1500.0
18        E502                 10/06/2022         16/06/2022         1900.0
19        E502                 10/07/2022         12/07/2022         1600.0
20        F601                 11/06/2022         17/06/2022         2000.0
21        F601                 11/07/2022         13/07/2022         1000.0
22        F602                 12/06/2022         15/06/2022         2100.0
23        F602                 12/07/2022         12/07/2022         1100.0
24        G701                 13/06/2022         19/06/2022         2200.0
25        G701                 13/07/2022         20/07/2022         1200.0
26        G702                 14/06/2022         15/06/2022         2300.0
27        G702                 14/07/2022         17/07/2022         2100.0
28        H801                 15/06/2022         18/06/2022         2400.0
29        H801                 15/07/2022         16/07/2022         2200.0

In [159]:
administracion_condominio_norm_2['datas_combinadas_pagamento'] = pd.to_datetime(administracion_condominio_norm_2['datas_combinadas_pagamento'], format='%d/%m/%Y')
administracion_condominio_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 1.1+ KB

In [161]:
administracion_condominio_norm_2['datas_de_pagamento'] = pd.to_datetime(administracion_condominio_norm_2['datas_de_pagamento'], format='%d/%m/%Y')
administracion_condominio_norm_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.1+ KB

In [162]:
administracion_condominio_norm_2['retrasado'] = (administracion_condominio_norm_2['datas_de_pagamento'] - administracion_condominio_norm_2['datas_combinadas_pagamento']).dt.days
administracion_condominio_norm_2

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,retrasado
0,A101,2022-06-01,2022-06-05,1000.0,4
1,A101,2022-07-01,2022-07-03,2500.0,2
2,A102,2022-06-02,2022-06-02,1100.0,0
3,A102,2022-07-02,2022-07-06,2600.0,4
4,B201,2022-06-03,2022-06-07,1200.0,4
5,B201,2022-07-03,2022-07-03,2700.0,0
6,B202,2022-06-04,2022-06-07,1300.0,3
7,B202,2022-07-04,2022-07-05,2800.0,1
8,C301,2022-06-05,2022-06-10,1400.0,5
9,C301,2022-07-05,2022-07-09,2900.0,4
10,C302,2022-06-06,2022-06-08,1500.0,2
11,C302,2022-07-06,2022-07-12,1200.0,6
12,D401,2022-06-07,2022-06-07,1600.0,0
13,D401,2022-07-07,2022-07-09,1300.0,2
14,D402,2022-06-08,2022-06-10,1700.0,2
15,D402,2022-07-08,2022-07-14,1400.0,6
16,E501,2022-06-09,2022-06-10,1800.0,1
17,E501,2022-07-09,2022-07-09,1500.0,0
18,E502,2022-06-10,2022-06-16,1900.0,6
19,E502,2022-07-10,2022-07-12,1600.0,2
20,F601,2022-06-11,2022-06-17,2000.0,6
21,F601,2022-07-11,2022-07-13,1000.0,2
22,F602,2022-06-12,2022-06-15,2100.0,3
23,F602,2022-07-12,2022-07-12,1100.0,0
24,G701,2022-06-13,2022-06-19,2200.0,6
25,G701,2022-07-13,2022-07-20,1200.0,7
26,G702,2022-06-14,2022-06-15,2300.0,1
27,G702,2022-07-14,2022-07-17,2100.0,3
28,H801,2022-06-15,2022-06-18,2400.0,3
29,H801,2022-07-15,2022-07-16,2200.0,1

In [164]:
promedio_retrasado = administracion_condominio_norm_2.groupby(['apartamento'])['retrasado'].mean()
promedio_retrasado

apartamento
A101    3.0
A102    2.0
B201    2.0
B202    2.0
C301    4.5
C302    4.0
D401    1.0
D402    4.0
E501    0.5
E502    4.0
F601    4.0
F602    1.5
G701    6.5
G702    2.0
H801    2.0
Name: retrasado, dtype: float64